kv:
  port: 8000
  refresh_timeout: 50s

balancer:
  port: 8080
  read_timeout: 2s
  write_timeout: 2s
  dial_timeout: 5s
  check_interval: 5s
  weight_coef: 1
  weight_max_step: 0.15
  weight_type: 1
  upstreams:
    - host: 'localhost'
      app_port: 8081
      service_port: 5000
      weight: 8
    - host: 'localhost'
      app_port: 8082
      service_port: 5001
      weight: 5
