kv:
  port: 8000
  start_version: 1
  refresh_timeout: 50s
balancer:
  upstreams:
    - host: 'localhost'
      app_port: 8081
      service_port: 5000
      weight: 8
    - host: 'localhost'
      app_port: 8082
      service_port: 5001
      weight: 5

  port: 8080
  read_timeout: 2s
  write_timeout: 2s
  dial_timeout: 5s
  check_interval: 5s